//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWTTransport.BLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJob
    {
        public int JobID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerCol { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<bool> SysCode { get; set; }
        public Nullable<System.DateTime> dtFrom { get; set; }
        public Nullable<System.DateTime> dtTo { get; set; }
        public string DriverName { get; set; }
        public string DriverInitials { get; set; }
        public Nullable<System.DateTime> DriverTimeStamp { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string MiscCode { get; set; }
        public Nullable<int> Type { get; set; }
        public string JobRef { get; set; }
        public string CustRef { get; set; }
        public string Area { get; set; }
        public string Journey { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string InvoiceNo { get; set; }
        public string Notes { get; set; }
        public Nullable<int> DuplicateOf { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> UseReturn { get; set; }
        public string Address { get; set; }
        public Nullable<int> TruckId { get; set; }
        public Nullable<int> TrailerId { get; set; }
        public string PinNumber { get; set; }
        public Nullable<int> Gen_Address { get; set; }
        public Nullable<int> Gen_Journey { get; set; }
        public Nullable<int> Gen_Notes { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
    }
}
